export const MOCK_CANDIDATE_POOL = [
  {
    id: "cand_lin_yuanan",
    displayName: "林予安",
    age: 30,
    city: "上海",
    occupation: "产品经理",
    relationshipGoal: "serious",
    marriageTimeline: "one_to_two_years",
    childrenPreference: "wants_children",
    familyBoundary: "independent",
    financialView: "practical",
    communicationStyle: "direct",
    verificationLevel: "已实名",
    trustLevel: "high",
    summary:
      "长期在上海工作，目标清晰，偏认真长期关系，婚后倾向独立小家庭，消费观务实。",
    searchableText:
      "上海 产品经理 认真长期 结婚 1到2年 独立小家庭 务实 理性消费 直接沟通 想要孩子 有房有贷 有车 收入稳定",
    riskTags: [],
    highlights: ["长期关系导向", "独立小家庭", "现实条件稳定"],
    incomeBand: "30k_to_50k",
    incomeStability: "stable",
    debtLevel: "mortgage_or_car_loan_only",
    housingStatus: "own_with_loan",
    vehicleStatus: "own",
    siblingStructure: "only_child",
    parentCareBurden: "medium",
    postMaritalLivingPreference: "independent_home"
  },
  {
    id: "cand_qin_yawen",
    displayName: "秦雅文",
    age: 29,
    city: "杭州",
    occupation: "医生",
    relationshipGoal: "serious",
    marriageTimeline: "one_to_two_years",
    childrenPreference: "wants_children",
    familyBoundary: "independent",
    financialView: "practical",
    communicationStyle: "steady",
    verificationLevel: "已实名",
    trustLevel: "high",
    summary:
      "生活节奏规律，长期目标明确，财务观与家庭边界偏稳健，但工作较忙，回复节奏不会太快。",
    searchableText:
      "杭州 医生 认真长期 1到2年结婚 想要孩子 独立小家庭 务实 稳定沟通 已实名 有房无贷 独生子女",
    riskTags: [],
    highlights: ["长期目标清晰", "生活规律", "整体稳健"],
    incomeBand: "30k_to_50k",
    incomeStability: "stable",
    debtLevel: "none_or_low",
    housingStatus: "own_without_loan",
    vehicleStatus: "none",
    siblingStructure: "only_child",
    parentCareBurden: "medium",
    postMaritalLivingPreference: "near_parents"
  },
  {
    id: "cand_zhou_qingzhi",
    displayName: "周清芷",
    age: 29,
    city: "杭州",
    occupation: "品牌策划",
    relationshipGoal: "serious",
    marriageTimeline: "open_ended",
    childrenPreference: "open",
    familyBoundary: "independent",
    financialView: "practical",
    communicationStyle: "steady",
    verificationLevel: "已实名",
    trustLevel: "high",
    summary:
      "关系目标认真，但结婚节奏偏慢，更希望先稳定相处后再决定下一步。",
    searchableText:
      "杭州 品牌策划 认真关系 暂不着急结婚 开放看待孩子 独立家庭 务实 稳定回复 独立租房 无车 有兄弟姐妹",
    riskTags: [],
    highlights: ["城市可匹配", "生活节奏稳定", "沟通耐心"],
    incomeBand: "15k_to_30k",
    incomeStability: "stable",
    debtLevel: "none_or_low",
    housingStatus: "renting_independently",
    vehicleStatus: "none",
    siblingStructure: "has_siblings",
    parentCareBurden: "medium",
    postMaritalLivingPreference: "independent_home"
  },
  {
    id: "cand_peng_haoran",
    displayName: "彭皓然",
    age: 31,
    city: "上海",
    occupation: "销售总监",
    relationshipGoal: "serious",
    marriageTimeline: "within_1_year",
    childrenPreference: "wants_children",
    familyBoundary: "family_led",
    financialView: "practical",
    communicationStyle: "direct",
    verificationLevel: "已实名",
    trustLevel: "medium",
    summary:
      "关系目标非常明确，推进速度较快，但原生家庭参与度偏高，婚后边界需要重点确认。",
    searchableText:
      "上海 销售总监 认真长期 1年内结婚 想要孩子 父母参与度高 务实 直接沟通 与父母同住 有车",
    riskTags: ["family_led"],
    highlights: ["目标清晰", "现实推进意愿强", "城市一致"],
    incomeBand: "30k_to_50k",
    incomeStability: "stable",
    debtLevel: "mortgage_or_car_loan_only",
    housingStatus: "living_with_parents",
    vehicleStatus: "own",
    siblingStructure: "has_siblings",
    parentCareBurden: "medium",
    postMaritalLivingPreference: "can_live_with_parents"
  },
  {
    id: "cand_he_mengqing",
    displayName: "何梦晴",
    age: 31,
    city: "上海",
    occupation: "投研顾问",
    relationshipGoal: "serious",
    marriageTimeline: "within_1_year",
    childrenPreference: "wants_children",
    familyBoundary: "family_led",
    financialView: "status_spending",
    communicationStyle: "direct",
    verificationLevel: "已实名",
    trustLevel: "medium",
    summary:
      "结婚意愿很强，但家庭参与度较高，也更重视生活品质和消费体验，适合推进节奏偏快的人。",
    searchableText:
      "上海 投研顾问 认真关系 1年内结婚 想要孩子 父母参与高 高消费 直接沟通 有房无贷 有车 独生子女",
    riskTags: ["family_led", "status_spending"],
    highlights: ["结婚推进意愿强", "表达直接", "现实资源充足"],
    incomeBand: "50k_plus",
    incomeStability: "stable",
    debtLevel: "none_or_low",
    housingStatus: "own_without_loan",
    vehicleStatus: "own",
    siblingStructure: "only_child",
    parentCareBurden: "high",
    postMaritalLivingPreference: "prefer_with_parents"
  },
  {
    id: "cand_tang_yiting",
    displayName: "唐意婷",
    age: 32,
    city: "深圳",
    occupation: "创业者",
    relationshipGoal: "serious",
    marriageTimeline: "within_1_year",
    childrenPreference: "wants_children",
    familyBoundary: "independent",
    financialView: "status_spending",
    communicationStyle: "direct",
    verificationLevel: "已实名",
    trustLevel: "medium",
    summary:
      "行动节奏快、结婚意愿强，但消费观偏激进，且异地迁移成本高。",
    searchableText:
      "深圳 创业者 认真关系 1年内结婚 想要孩子 独立家庭 高消费 频繁出差 迁移成本高 有车 租房",
    riskTags: ["status_spending", "high_mobility"],
    highlights: ["目标明确", "推进速度快", "跨城成本较高"],
    incomeBand: "50k_plus",
    incomeStability: "variable",
    debtLevel: "manageable_consumer_debt",
    housingStatus: "renting_independently",
    vehicleStatus: "own",
    siblingStructure: "has_siblings",
    parentCareBurden: "low",
    postMaritalLivingPreference: "independent_home"
  },
  {
    id: "cand_xu_jiamu",
    displayName: "徐嘉木",
    age: 28,
    city: "苏州",
    occupation: "游戏策划",
    relationshipGoal: "exploratory",
    marriageTimeline: "open_ended",
    childrenPreference: "unknown",
    familyBoundary: "unknown",
    financialView: "unknown",
    communicationStyle: "slow_burn",
    verificationLevel: "基础认证",
    trustLevel: "medium",
    summary:
      "更偏轻松接触和慢热观察，很多现实议题还没有明确态度，不适合快速推进。",
    searchableText:
      "苏州 游戏策划 先了解看看 暂不着急 慢热 低频沟通 基础认证 居住未固定 无车 调整期",
    riskTags: ["exploratory_goal", "low_verification"],
    highlights: ["低压力了解", "可先观察", "现实信息较少"],
    incomeBand: "below_15k",
    incomeStability: "currently_adjusting",
    debtLevel: "manageable_consumer_debt",
    housingStatus: "not_fixed",
    vehicleStatus: "none",
    siblingStructure: "has_siblings",
    parentCareBurden: "medium",
    postMaritalLivingPreference: "near_parents"
  },
  {
    id: "cand_chen_xingye",
    displayName: "陈星野",
    age: 30,
    city: "上海",
    occupation: "自由摄影师",
    relationshipGoal: "exploratory",
    marriageTimeline: "open_ended",
    childrenPreference: "no_children",
    familyBoundary: "independent",
    financialView: "unknown",
    communicationStyle: "direct",
    verificationLevel: "基础认证",
    trustLevel: "low",
    summary:
      "关系与孩子态度都更自由开放，适合暂不考虑长期承诺的人，不适合强长期、强婚育导向用户。",
    searchableText:
      "上海 自由摄影师 随缘 不要孩子 独立生活 直接沟通 基础认证 租房 无车 收入波动",
    riskTags: ["exploratory_goal", "low_verification", "childfree_conflict"],
    highlights: ["表达直接", "生活方式自由", "长期目标较弱"],
    incomeBand: "15k_to_30k",
    incomeStability: "variable",
    debtLevel: "none_or_low",
    housingStatus: "renting_independently",
    vehicleStatus: "none",
    siblingStructure: "has_siblings",
    parentCareBurden: "low",
    postMaritalLivingPreference: "independent_home"
  }
];
